### PR TITLE
IVideo ImageArray fix

### PR DESCRIPTION
**Pull request by hpavlov**
…ased on documentation) when creating an ImageArray from a bitmap; (2) made the helper methods creating bitmaps from image array work with bot row-major and column-major formats.

### CODE REVIEW

**Comment by Peter-Simpson** [comment]
Hi Hristo,

I've accepted your pull request and am building a release for Rick to test. I do have one possible concern, namely that the signature of this method has changed because it now has an additional bool  isRowMajor parameter.

> internal int GetColourBitmapPixels(int width, int height, int bpp, FlipMode flipMode, int[, ,] pixels, bool isRowMajor, ref byte[] bitmapBytes)

I'm wondering whether this is a breaking change? Should there also be a method overload that has an identical signature to the original and that calls your new method with a default value for isRowmajor?

Regards, Peter

**Comment by hpavlov** [comment]
Hi Peter,
This could be seen as a breaking change if someone was using the C function directly. I think that no one is supposed to do that. As long as all usage goes via the ASCOM.Utilities.Video.dll .NET assembly then all should be fine.
Also the old version of the method was wrong. If I keep the old method with the old implementation then it will still be wrong. If I keep the old method but fix the implementation then this can be also seen as breaking change. Therefore I think that updating the signature and providing the correct implementation should be okay.
I'me happy to be convinced otherwise.
Hristo.

    On Monday, April 27, 2020, 06:32:20 PM GMT+1, Peter Simpson <notifications@github.com> wrote:  
 
 


Hi Hristo,

I've accepted your pull request and am building a release for Rick to test. I do have one possible concern, namely that the signature of this method has changed because it now has an additional bool isRowMajor parameter.


internal int GetColourBitmapPixels(int width, int height, int bpp, FlipMode flipMode, int[, ,] pixels, bool isRowMajor, ref byte[] bitmapBytes)


I'm wondering whether this is a breaking change? Should there also be a method overload that has an identical signature to the original and that calls your new method with a default value for isRowmajor?

Regards, Peter

**Comment by Peter-Simpson** [comment]
Hi Hristo,

OK, thanks, if you are confident that the DLL is only used by the Platform the change is fine..

Best wishes, Peter

**Comment by Peter-Simpson** [comment]
Hi Hristo,

I've just run the Diagnostics test program and I'm now getting different pixel arrays back from the GetColourPixelsFromBitmap and PrepareBitMapForDisplay methods. Please can you confirm that this is expected as a result of the fix?

Thanks, Peter

20:17:29.788 Error                     VideoUtilsTests - ##### NOT Matched - GetColourPixelsFromBitmap FlipNone CheckSum - Received: "46339131", Expected: "55234894"
20:17:29.788 Error                     VideoUtilsTests - ##### NOT Matched - GetColourPixelsFromBitmap FlipHorizontally CheckSum - Received: "48230303", Expected: "54805394"
20:17:29.788 Error                     VideoUtilsTests - ##### NOT Matched - GetColourPixelsFromBitmap FlipVertically CheckSum - Received: "47516215", Expected: "54831409"
20:17:29.789 Error                     VideoUtilsTests - ##### NOT Matched - GetColourPixelsFromBitmap FlipBoth CheckSum - Received: "51308622", Expected: "53990701"
20:17:29.789 Error                     VideoUtilsTests - ##### NOT Matched - PrepareBitmapForDisplay None CheckSum - Received: "1650548", Expected: "243107340"
20:17:29.789 Error                     VideoUtilsTests - ##### NOT Matched - PrepareBitmapForDisplay FlipHorizontally CheckSum - Received: "1644236", Expected: "243407028"
20:17:29.789 Error                     VideoUtilsTests - ##### NOT Matched - PrepareBitmapForDisplay FlipVertically CheckSum - Received: "1674135", Expected: "243130927"
20:17:29.789 Error                     VideoUtilsTests - ##### NOT Matched - PrepareBitmapForDisplay FlipBoth CheckSum - Received: "1667823", Expected: "243430615"

**Pull request merged**
